import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";

const poppins = Source_Sans_3({
  subsets: ["latin"],
  variable: "--Source_Sans_3",
  weight: ["500"],
});

export const metadata = {
  title: "health-hub - home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={poppins.variable}>
        <Navbar></Navbar>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
